# Generated by Django 2.2.3 on 2019-10-06 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_num', models.TextField()),
                ('roll', models.TextField()),
                ('dept', models.TextField()),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('mark', models.IntegerField(default=1)),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
