# Generated by Django 2.2.3 on 2019-10-06 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stud',
            new_name='Student',
        ),
    ]
