# Generated by Django 2.2.3 on 2019-10-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191006_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_num',
            field=models.CharField(max_length=255),
        ),
    ]
