# Generated by Django 2.2.3 on 2019-10-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191006_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stud_num',
            new_name='student_num',
        ),
    ]
